#
# Module manifest for module 'RabbitMQ Power Shell Client library'
#
# Generated by: Mariusz Wojcik
#
# Generated on: 01/12/2016
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'dbe20433-01c6-43f9-b5d8-b6bb5241f500'

# Author of this module
Author = 'Mariusz Wojcik'

# Company or vendor of this module
CompanyName = 'Casper Solutions'

# Copyright statement for this module
Copyright = '(c) 2016 Mariusz Wojcik. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module containing RabbitMQ client functions'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
#ScriptsToProcess = @(
#    'PreventUnEscapeDotsAndSlashesOnUri.ps1',
#    'Invoke_RestMethodProxy.ps1',
#    'TabExpansions.ps1'
#  
#)

ModuleToProcess    = @("RabbitMQ-PowerShell-Client.psm1")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
    'Entities.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'createModel.ps1'
    'sendItemsToOutput.ps1'

    'New-RabbitMQConnection.ps1'
    'New-RabbitMQModel.ps1'
    'Measure-RabbitMQQueue.ps1'
    'Read-RabbitMQMessage.ps1'
    'Remove-RabbitMQMessage.ps1'
)

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

